version: '3.8'

services:
  order-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: order-backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb+srv://admin:Admin123@ordermanagementdb.tg6u4oj.mongodb.net/?retryWrites=true&w=majority&appName=OrderManagementDB
      - PORT=5000
    volumes:
      - .:/order-service/backend
    restart: always
