apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-backend
  template:
    metadata:
      labels:
        app: order-backend
    spec:
      containers:
        - name: order-backend
          image: your-dockerhub-username/order-backend:latest # Change this after pushing image to Docker Hub
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_URI
              value: mongodb+srv://admin:Admin123@ordermanagementdb.tg6u4oj.mongodb.net/?retryWrites=true&w=majority&appName=OrderManagementDB
            - name: PORT
              value: "5000"
