apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: restaurant-service
  template:
    metadata:
      labels:
        app: restaurant-service
    spec:
      containers:
      - name: restaurant-service
        image: restaurant-service:latest
        imagePullPolicy: Never  # For local testing
        ports:
        - containerPort: 5001
        env:
        - name: MONGO_URI
          value: "mongodb://mongo:27017/restaurant-service"
        - name: PORT
          value: "5001"