apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: notification-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5002
          env:
            - name: PORT
              value: "5002"
            - name: MAIL_USER
              value: "vilansiriwardana@gmail.com"
            - name: MAIL_PASSWORD
              value: "jtvbkztuckyatgzs"
            - name: APP_NAME
              value: "YumGo"
            - name: TWILIO_ACCOUNT_SID
              value: "AC196e600504758c61e1b76eb34589a971"
            - name: TWILIO_AUTH_TOKEN
              value: "fdc4507821b80c9abbdf2658b9ad0179"
            - name: TWILIO_PHONE_NUMBER
              value: "+19146136589"
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  selector:
    app: notification-service
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002
  type: ClusterIP
