apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: user-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 4000
          env:
            - name: PORT
              value: "4000"
            - name: MONGODB_URI
              value: "mongodb+srv://vilansiriwardana:dsprojectdb@dsprojectdb.ezmimy7.mongodb.net/?retryWrites=true&w=majority&appName=DSProjectDB"
            - name: NOTIFICATION_SERVICE_URL
              value: "http://notification-service:5002"
            - name: JWT_SECRET
              value: "yoursecretkey"
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
  type: ClusterIP
